"$schema" = "schemas/schema.json"
[default]
description = "Allows initializing the plugin and reading wz files"
permissions = [
  "allow-init",
  "allow-get-png",
  "allow-get-json",
  "allow-parse-node",
  "allow-unparse-node",
  "allow-get-node-info",
  "allow-get-children",
  "allow-parse-children"
]