/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppSkillsImport } from './routes/_app/skills'
import { Route as AppQuestsImport } from './routes/_app/quests'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppSkillsSearchImport } from './routes/_app/skills/search'
import { Route as AppQuestsSearchImport } from './routes/_app/quests/search'
import { Route as AppQuestsCategoriesImport } from './routes/_app/quests/categories'
import { Route as AppSkillsExportIndexImport } from './routes/_app/skills/export/index'
import { Route as AppSkillsCategoriesIndexImport } from './routes/_app/skills/categories/index'
import { Route as AppQuestsCategoriesIndexImport } from './routes/_app/quests/categories/index'
import { Route as AppSkillsSIdImport } from './routes/_app/skills/s/$id'
import { Route as AppSkillsCategoriesIdImport } from './routes/_app/skills/categories/$id'
import { Route as AppQuestsQIdImport } from './routes/_app/quests/q/$id'
import { Route as AppQuestsCategoriesIdImport } from './routes/_app/quests/categories/$id'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppSkillsRoute = AppSkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)

const AppQuestsRoute = AppQuestsImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppSkillsSearchRoute = AppSkillsSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppSkillsRoute,
} as any)

const AppQuestsSearchRoute = AppQuestsSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppQuestsRoute,
} as any)

const AppQuestsCategoriesRoute = AppQuestsCategoriesImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppQuestsRoute,
} as any)

const AppSkillsExportIndexRoute = AppSkillsExportIndexImport.update({
  id: '/export/',
  path: '/export/',
  getParentRoute: () => AppSkillsRoute,
} as any)

const AppSkillsCategoriesIndexRoute = AppSkillsCategoriesIndexImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppSkillsRoute,
} as any)

const AppQuestsCategoriesIndexRoute = AppQuestsCategoriesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuestsCategoriesRoute,
} as any)

const AppSkillsSIdRoute = AppSkillsSIdImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => AppSkillsRoute,
} as any)

const AppSkillsCategoriesIdRoute = AppSkillsCategoriesIdImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => AppSkillsRoute,
} as any)

const AppQuestsQIdRoute = AppQuestsQIdImport.update({
  id: '/q/$id',
  path: '/q/$id',
  getParentRoute: () => AppQuestsRoute,
} as any)

const AppQuestsCategoriesIdRoute = AppQuestsCategoriesIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppQuestsCategoriesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/_app/quests': {
      id: '/_app/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AppQuestsImport
      parentRoute: typeof AppImport
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsImport
      parentRoute: typeof AppImport
    }
    '/_app/quests/categories': {
      id: '/_app/quests/categories'
      path: '/categories'
      fullPath: '/quests/categories'
      preLoaderRoute: typeof AppQuestsCategoriesImport
      parentRoute: typeof AppQuestsImport
    }
    '/_app/quests/search': {
      id: '/_app/quests/search'
      path: '/search'
      fullPath: '/quests/search'
      preLoaderRoute: typeof AppQuestsSearchImport
      parentRoute: typeof AppQuestsImport
    }
    '/_app/skills/search': {
      id: '/_app/skills/search'
      path: '/search'
      fullPath: '/skills/search'
      preLoaderRoute: typeof AppSkillsSearchImport
      parentRoute: typeof AppSkillsImport
    }
    '/_app/quests/categories/$id': {
      id: '/_app/quests/categories/$id'
      path: '/$id'
      fullPath: '/quests/categories/$id'
      preLoaderRoute: typeof AppQuestsCategoriesIdImport
      parentRoute: typeof AppQuestsCategoriesImport
    }
    '/_app/quests/q/$id': {
      id: '/_app/quests/q/$id'
      path: '/q/$id'
      fullPath: '/quests/q/$id'
      preLoaderRoute: typeof AppQuestsQIdImport
      parentRoute: typeof AppQuestsImport
    }
    '/_app/skills/categories/$id': {
      id: '/_app/skills/categories/$id'
      path: '/categories/$id'
      fullPath: '/skills/categories/$id'
      preLoaderRoute: typeof AppSkillsCategoriesIdImport
      parentRoute: typeof AppSkillsImport
    }
    '/_app/skills/s/$id': {
      id: '/_app/skills/s/$id'
      path: '/s/$id'
      fullPath: '/skills/s/$id'
      preLoaderRoute: typeof AppSkillsSIdImport
      parentRoute: typeof AppSkillsImport
    }
    '/_app/quests/categories/': {
      id: '/_app/quests/categories/'
      path: '/'
      fullPath: '/quests/categories/'
      preLoaderRoute: typeof AppQuestsCategoriesIndexImport
      parentRoute: typeof AppQuestsCategoriesImport
    }
    '/_app/skills/categories/': {
      id: '/_app/skills/categories/'
      path: '/categories'
      fullPath: '/skills/categories'
      preLoaderRoute: typeof AppSkillsCategoriesIndexImport
      parentRoute: typeof AppSkillsImport
    }
    '/_app/skills/export/': {
      id: '/_app/skills/export/'
      path: '/export'
      fullPath: '/skills/export'
      preLoaderRoute: typeof AppSkillsExportIndexImport
      parentRoute: typeof AppSkillsImport
    }
  }
}

// Create and export the route tree

interface AppQuestsCategoriesRouteChildren {
  AppQuestsCategoriesIdRoute: typeof AppQuestsCategoriesIdRoute
  AppQuestsCategoriesIndexRoute: typeof AppQuestsCategoriesIndexRoute
}

const AppQuestsCategoriesRouteChildren: AppQuestsCategoriesRouteChildren = {
  AppQuestsCategoriesIdRoute: AppQuestsCategoriesIdRoute,
  AppQuestsCategoriesIndexRoute: AppQuestsCategoriesIndexRoute,
}

const AppQuestsCategoriesRouteWithChildren =
  AppQuestsCategoriesRoute._addFileChildren(AppQuestsCategoriesRouteChildren)

interface AppQuestsRouteChildren {
  AppQuestsCategoriesRoute: typeof AppQuestsCategoriesRouteWithChildren
  AppQuestsSearchRoute: typeof AppQuestsSearchRoute
  AppQuestsQIdRoute: typeof AppQuestsQIdRoute
}

const AppQuestsRouteChildren: AppQuestsRouteChildren = {
  AppQuestsCategoriesRoute: AppQuestsCategoriesRouteWithChildren,
  AppQuestsSearchRoute: AppQuestsSearchRoute,
  AppQuestsQIdRoute: AppQuestsQIdRoute,
}

const AppQuestsRouteWithChildren = AppQuestsRoute._addFileChildren(
  AppQuestsRouteChildren,
)

interface AppSkillsRouteChildren {
  AppSkillsSearchRoute: typeof AppSkillsSearchRoute
  AppSkillsCategoriesIdRoute: typeof AppSkillsCategoriesIdRoute
  AppSkillsSIdRoute: typeof AppSkillsSIdRoute
  AppSkillsCategoriesIndexRoute: typeof AppSkillsCategoriesIndexRoute
  AppSkillsExportIndexRoute: typeof AppSkillsExportIndexRoute
}

const AppSkillsRouteChildren: AppSkillsRouteChildren = {
  AppSkillsSearchRoute: AppSkillsSearchRoute,
  AppSkillsCategoriesIdRoute: AppSkillsCategoriesIdRoute,
  AppSkillsSIdRoute: AppSkillsSIdRoute,
  AppSkillsCategoriesIndexRoute: AppSkillsCategoriesIndexRoute,
  AppSkillsExportIndexRoute: AppSkillsExportIndexRoute,
}

const AppSkillsRouteWithChildren = AppSkillsRoute._addFileChildren(
  AppSkillsRouteChildren,
)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppQuestsRoute: typeof AppQuestsRouteWithChildren
  AppSkillsRoute: typeof AppSkillsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppQuestsRoute: AppQuestsRouteWithChildren,
  AppSkillsRoute: AppSkillsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/home': typeof AppHomeRoute
  '/quests': typeof AppQuestsRouteWithChildren
  '/skills': typeof AppSkillsRouteWithChildren
  '/quests/categories': typeof AppQuestsCategoriesRouteWithChildren
  '/quests/search': typeof AppQuestsSearchRoute
  '/skills/search': typeof AppSkillsSearchRoute
  '/quests/categories/$id': typeof AppQuestsCategoriesIdRoute
  '/quests/q/$id': typeof AppQuestsQIdRoute
  '/skills/categories/$id': typeof AppSkillsCategoriesIdRoute
  '/skills/s/$id': typeof AppSkillsSIdRoute
  '/quests/categories/': typeof AppQuestsCategoriesIndexRoute
  '/skills/categories': typeof AppSkillsCategoriesIndexRoute
  '/skills/export': typeof AppSkillsExportIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/home': typeof AppHomeRoute
  '/quests': typeof AppQuestsRouteWithChildren
  '/skills': typeof AppSkillsRouteWithChildren
  '/quests/search': typeof AppQuestsSearchRoute
  '/skills/search': typeof AppSkillsSearchRoute
  '/quests/categories/$id': typeof AppQuestsCategoriesIdRoute
  '/quests/q/$id': typeof AppQuestsQIdRoute
  '/skills/categories/$id': typeof AppSkillsCategoriesIdRoute
  '/skills/s/$id': typeof AppSkillsSIdRoute
  '/quests/categories': typeof AppQuestsCategoriesIndexRoute
  '/skills/categories': typeof AppSkillsCategoriesIndexRoute
  '/skills/export': typeof AppSkillsExportIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/quests': typeof AppQuestsRouteWithChildren
  '/_app/skills': typeof AppSkillsRouteWithChildren
  '/_app/quests/categories': typeof AppQuestsCategoriesRouteWithChildren
  '/_app/quests/search': typeof AppQuestsSearchRoute
  '/_app/skills/search': typeof AppSkillsSearchRoute
  '/_app/quests/categories/$id': typeof AppQuestsCategoriesIdRoute
  '/_app/quests/q/$id': typeof AppQuestsQIdRoute
  '/_app/skills/categories/$id': typeof AppSkillsCategoriesIdRoute
  '/_app/skills/s/$id': typeof AppSkillsSIdRoute
  '/_app/quests/categories/': typeof AppQuestsCategoriesIndexRoute
  '/_app/skills/categories/': typeof AppSkillsCategoriesIndexRoute
  '/_app/skills/export/': typeof AppSkillsExportIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/home'
    | '/quests'
    | '/skills'
    | '/quests/categories'
    | '/quests/search'
    | '/skills/search'
    | '/quests/categories/$id'
    | '/quests/q/$id'
    | '/skills/categories/$id'
    | '/skills/s/$id'
    | '/quests/categories/'
    | '/skills/categories'
    | '/skills/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/home'
    | '/quests'
    | '/skills'
    | '/quests/search'
    | '/skills/search'
    | '/quests/categories/$id'
    | '/quests/q/$id'
    | '/skills/categories/$id'
    | '/skills/s/$id'
    | '/quests/categories'
    | '/skills/categories'
    | '/skills/export'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/home'
    | '/_app/quests'
    | '/_app/skills'
    | '/_app/quests/categories'
    | '/_app/quests/search'
    | '/_app/skills/search'
    | '/_app/quests/categories/$id'
    | '/_app/quests/q/$id'
    | '/_app/skills/categories/$id'
    | '/_app/skills/s/$id'
    | '/_app/quests/categories/'
    | '/_app/skills/categories/'
    | '/_app/skills/export/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/home",
        "/_app/quests",
        "/_app/skills"
      ]
    },
    "/_app/home": {
      "filePath": "_app/home.tsx",
      "parent": "/_app"
    },
    "/_app/quests": {
      "filePath": "_app/quests.tsx",
      "parent": "/_app",
      "children": [
        "/_app/quests/categories",
        "/_app/quests/search",
        "/_app/quests/q/$id"
      ]
    },
    "/_app/skills": {
      "filePath": "_app/skills.tsx",
      "parent": "/_app",
      "children": [
        "/_app/skills/search",
        "/_app/skills/categories/$id",
        "/_app/skills/s/$id",
        "/_app/skills/categories/",
        "/_app/skills/export/"
      ]
    },
    "/_app/quests/categories": {
      "filePath": "_app/quests/categories.tsx",
      "parent": "/_app/quests",
      "children": [
        "/_app/quests/categories/$id",
        "/_app/quests/categories/"
      ]
    },
    "/_app/quests/search": {
      "filePath": "_app/quests/search.tsx",
      "parent": "/_app/quests"
    },
    "/_app/skills/search": {
      "filePath": "_app/skills/search.tsx",
      "parent": "/_app/skills"
    },
    "/_app/quests/categories/$id": {
      "filePath": "_app/quests/categories/$id.tsx",
      "parent": "/_app/quests/categories"
    },
    "/_app/quests/q/$id": {
      "filePath": "_app/quests/q/$id.tsx",
      "parent": "/_app/quests"
    },
    "/_app/skills/categories/$id": {
      "filePath": "_app/skills/categories/$id.tsx",
      "parent": "/_app/skills"
    },
    "/_app/skills/s/$id": {
      "filePath": "_app/skills/s/$id.tsx",
      "parent": "/_app/skills"
    },
    "/_app/quests/categories/": {
      "filePath": "_app/quests/categories/index.tsx",
      "parent": "/_app/quests/categories"
    },
    "/_app/skills/categories/": {
      "filePath": "_app/skills/categories/index.tsx",
      "parent": "/_app/skills"
    },
    "/_app/skills/export/": {
      "filePath": "_app/skills/export/index.tsx",
      "parent": "/_app/skills"
    }
  }
}
ROUTE_MANIFEST_END */
