/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppQuestsSearchImport } from './routes/_app/quests/search'
import { Route as AppQuestsCategoriesImport } from './routes/_app/quests/categories'
import { Route as AppQuestsIdImport } from './routes/_app/quests/$id'
import { Route as AppQuestsCategoriesIndexImport } from './routes/_app/quests/categories/index'
import { Route as AppQuestsCategoriesIdImport } from './routes/_app/quests/categories/$id'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppQuestsSearchRoute = AppQuestsSearchImport.update({
  id: '/quests/search',
  path: '/quests/search',
  getParentRoute: () => AppRoute,
} as any)

const AppQuestsCategoriesRoute = AppQuestsCategoriesImport.update({
  id: '/quests/categories',
  path: '/quests/categories',
  getParentRoute: () => AppRoute,
} as any)

const AppQuestsIdRoute = AppQuestsIdImport.update({
  id: '/quests/$id',
  path: '/quests/$id',
  getParentRoute: () => AppRoute,
} as any)

const AppQuestsCategoriesIndexRoute = AppQuestsCategoriesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuestsCategoriesRoute,
} as any)

const AppQuestsCategoriesIdRoute = AppQuestsCategoriesIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppQuestsCategoriesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/_app/quests/$id': {
      id: '/_app/quests/$id'
      path: '/quests/$id'
      fullPath: '/quests/$id'
      preLoaderRoute: typeof AppQuestsIdImport
      parentRoute: typeof AppImport
    }
    '/_app/quests/categories': {
      id: '/_app/quests/categories'
      path: '/quests/categories'
      fullPath: '/quests/categories'
      preLoaderRoute: typeof AppQuestsCategoriesImport
      parentRoute: typeof AppImport
    }
    '/_app/quests/search': {
      id: '/_app/quests/search'
      path: '/quests/search'
      fullPath: '/quests/search'
      preLoaderRoute: typeof AppQuestsSearchImport
      parentRoute: typeof AppImport
    }
    '/_app/quests/categories/$id': {
      id: '/_app/quests/categories/$id'
      path: '/$id'
      fullPath: '/quests/categories/$id'
      preLoaderRoute: typeof AppQuestsCategoriesIdImport
      parentRoute: typeof AppQuestsCategoriesImport
    }
    '/_app/quests/categories/': {
      id: '/_app/quests/categories/'
      path: '/'
      fullPath: '/quests/categories/'
      preLoaderRoute: typeof AppQuestsCategoriesIndexImport
      parentRoute: typeof AppQuestsCategoriesImport
    }
  }
}

// Create and export the route tree

interface AppQuestsCategoriesRouteChildren {
  AppQuestsCategoriesIdRoute: typeof AppQuestsCategoriesIdRoute
  AppQuestsCategoriesIndexRoute: typeof AppQuestsCategoriesIndexRoute
}

const AppQuestsCategoriesRouteChildren: AppQuestsCategoriesRouteChildren = {
  AppQuestsCategoriesIdRoute: AppQuestsCategoriesIdRoute,
  AppQuestsCategoriesIndexRoute: AppQuestsCategoriesIndexRoute,
}

const AppQuestsCategoriesRouteWithChildren =
  AppQuestsCategoriesRoute._addFileChildren(AppQuestsCategoriesRouteChildren)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppQuestsIdRoute: typeof AppQuestsIdRoute
  AppQuestsCategoriesRoute: typeof AppQuestsCategoriesRouteWithChildren
  AppQuestsSearchRoute: typeof AppQuestsSearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppQuestsIdRoute: AppQuestsIdRoute,
  AppQuestsCategoriesRoute: AppQuestsCategoriesRouteWithChildren,
  AppQuestsSearchRoute: AppQuestsSearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/home': typeof AppHomeRoute
  '/quests/$id': typeof AppQuestsIdRoute
  '/quests/categories': typeof AppQuestsCategoriesRouteWithChildren
  '/quests/search': typeof AppQuestsSearchRoute
  '/quests/categories/$id': typeof AppQuestsCategoriesIdRoute
  '/quests/categories/': typeof AppQuestsCategoriesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/home': typeof AppHomeRoute
  '/quests/$id': typeof AppQuestsIdRoute
  '/quests/search': typeof AppQuestsSearchRoute
  '/quests/categories/$id': typeof AppQuestsCategoriesIdRoute
  '/quests/categories': typeof AppQuestsCategoriesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/quests/$id': typeof AppQuestsIdRoute
  '/_app/quests/categories': typeof AppQuestsCategoriesRouteWithChildren
  '/_app/quests/search': typeof AppQuestsSearchRoute
  '/_app/quests/categories/$id': typeof AppQuestsCategoriesIdRoute
  '/_app/quests/categories/': typeof AppQuestsCategoriesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/home'
    | '/quests/$id'
    | '/quests/categories'
    | '/quests/search'
    | '/quests/categories/$id'
    | '/quests/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/home'
    | '/quests/$id'
    | '/quests/search'
    | '/quests/categories/$id'
    | '/quests/categories'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/home'
    | '/_app/quests/$id'
    | '/_app/quests/categories'
    | '/_app/quests/search'
    | '/_app/quests/categories/$id'
    | '/_app/quests/categories/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/home",
        "/_app/quests/$id",
        "/_app/quests/categories",
        "/_app/quests/search"
      ]
    },
    "/_app/home": {
      "filePath": "_app/home.tsx",
      "parent": "/_app"
    },
    "/_app/quests/$id": {
      "filePath": "_app/quests/$id.tsx",
      "parent": "/_app"
    },
    "/_app/quests/categories": {
      "filePath": "_app/quests/categories.tsx",
      "parent": "/_app",
      "children": [
        "/_app/quests/categories/$id",
        "/_app/quests/categories/"
      ]
    },
    "/_app/quests/search": {
      "filePath": "_app/quests/search.tsx",
      "parent": "/_app"
    },
    "/_app/quests/categories/$id": {
      "filePath": "_app/quests/categories/$id.tsx",
      "parent": "/_app/quests/categories"
    },
    "/_app/quests/categories/": {
      "filePath": "_app/quests/categories/index.tsx",
      "parent": "/_app/quests/categories"
    }
  }
}
ROUTE_MANIFEST_END */
